// GENERATED by scripts/gen-types.ts from supabase/migrations — do not edit by hand.
// Regenerate with `npm run types:gen`. A vitest check fails when this file is stale.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          id: number;
          actor_id: string | null;
          actor_role: Database["public"]["Enums"]["user_role"] | null;
          action: string;
          entity_type: string | null;
          entity_id: string | null;
          before: Json | null;
          after: Json | null;
          reason: string | null;
          ip: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          actor_id?: string | null;
          actor_role?: Database["public"]["Enums"]["user_role"] | null;
          action: string;
          entity_type?: string | null;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          reason?: string | null;
          ip?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          actor_id?: string | null;
          actor_role?: Database["public"]["Enums"]["user_role"] | null;
          action?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          reason?: string | null;
          ip?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      canned_responses: {
        Row: {
          id: string;
          title: string;
          body_md: string;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          body_md: string;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          body_md?: string;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      contact_messages: {
        Row: {
          id: string;
          name: string;
          email: string;
          topic: string | null;
          message: string;
          status: string;
          ip: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          topic?: string | null;
          message: string;
          status?: string;
          ip?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          topic?: string | null;
          message?: string;
          status?: string;
          ip?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      coupon_redemptions: {
        Row: {
          id: string;
          coupon_id: string;
          user_id: string;
          order_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          coupon_id: string;
          user_id: string;
          order_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          coupon_id?: string;
          user_id?: string;
          order_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      coupons: {
        Row: {
          id: string;
          code: string;
          type: Database["public"]["Enums"]["discount_type"];
          value: number;
          applies_product: Database["public"]["Enums"]["product_type"] | null;
          applies_plan_id: string | null;
          applies_location_id: string | null;
          min_order_cents: number;
          max_redemptions: number | null;
          per_user_limit: number | null;
          redeemed_count: number;
          starts_at: string | null;
          ends_at: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          type: Database["public"]["Enums"]["discount_type"];
          value: number;
          applies_product?: Database["public"]["Enums"]["product_type"] | null;
          applies_plan_id?: string | null;
          applies_location_id?: string | null;
          min_order_cents?: number;
          max_redemptions?: number | null;
          per_user_limit?: number | null;
          redeemed_count?: number;
          starts_at?: string | null;
          ends_at?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          type?: Database["public"]["Enums"]["discount_type"];
          value?: number;
          applies_product?: Database["public"]["Enums"]["product_type"] | null;
          applies_plan_id?: string | null;
          applies_location_id?: string | null;
          min_order_cents?: number;
          max_redemptions?: number | null;
          per_user_limit?: number | null;
          redeemed_count?: number;
          starts_at?: string | null;
          ends_at?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      email_outbox: {
        Row: {
          id: string;
          user_id: string | null;
          to_email: string;
          template: string;
          data: Json;
          status: string;
          attempts: number;
          last_error: string | null;
          send_after: string;
          sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          to_email: string;
          template: string;
          data?: Json;
          status?: string;
          attempts?: number;
          last_error?: string | null;
          send_after?: string;
          sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          to_email?: string;
          template?: string;
          data?: Json;
          status?: string;
          attempts?: number;
          last_error?: string | null;
          send_after?: string;
          sent_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      faqs: {
        Row: {
          id: string;
          slug: string;
          category: string;
          question: string;
          answer_md: string;
          sort_order: number;
          is_published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          category?: string;
          question: string;
          answer_md: string;
          sort_order?: number;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          category?: string;
          question?: string;
          answer_md?: string;
          sort_order?: number;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      inventory_items: {
        Row: {
          id: string;
          product: Database["public"]["Enums"]["product_type"];
          location_id: string;
          plan_id: string | null;
          ip: string;
          rdp_port: number;
          username: string;
          password_enc: string;
          supplier: string | null;
          supplier_ref: string | null;
          supplier_cost_cents: number | null;
          supplier_expires_at: string | null;
          status: Database["public"]["Enums"]["inventory_status"];
          allocated_service_id: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product: Database["public"]["Enums"]["product_type"];
          location_id: string;
          plan_id?: string | null;
          ip: string;
          rdp_port?: number;
          username: string;
          password_enc: string;
          supplier?: string | null;
          supplier_ref?: string | null;
          supplier_cost_cents?: number | null;
          supplier_expires_at?: string | null;
          status?: Database["public"]["Enums"]["inventory_status"];
          allocated_service_id?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          product?: Database["public"]["Enums"]["product_type"];
          location_id?: string;
          plan_id?: string | null;
          ip?: string;
          rdp_port?: number;
          username?: string;
          password_enc?: string;
          supplier?: string | null;
          supplier_ref?: string | null;
          supplier_cost_cents?: number | null;
          supplier_expires_at?: string | null;
          status?: Database["public"]["Enums"]["inventory_status"];
          allocated_service_id?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      invoices: {
        Row: {
          id: string;
          invoice_number: string;
          order_id: string;
          payment_id: string | null;
          user_id: string;
          subtotal_cents: number;
          discount_cents: number;
          total_cents: number;
          currency: string;
          status: string;
          void_reason: string | null;
          issued_at: string;
          billing_snapshot: Json;
        };
        Insert: {
          id?: string;
          invoice_number?: string;
          order_id: string;
          payment_id?: string | null;
          user_id: string;
          subtotal_cents: number;
          discount_cents?: number;
          total_cents: number;
          currency?: string;
          status?: string;
          void_reason?: string | null;
          issued_at?: string;
          billing_snapshot?: Json;
        };
        Update: {
          id?: string;
          invoice_number?: string;
          order_id?: string;
          payment_id?: string | null;
          user_id?: string;
          subtotal_cents?: number;
          discount_cents?: number;
          total_cents?: number;
          currency?: string;
          status?: string;
          void_reason?: string | null;
          issued_at?: string;
          billing_snapshot?: Json;
        };
        Relationships: [];
      };
      locations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          iso2: string;
          image_key: string | null;
          blurb: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          iso2: string;
          image_key?: string | null;
          blurb?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          iso2?: string;
          image_key?: string | null;
          blurb?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          body: string | null;
          link: string | null;
          data: Json;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          body?: string | null;
          link?: string | null;
          data?: Json;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          title?: string;
          body?: string | null;
          link?: string | null;
          data?: Json;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      order_events: {
        Row: {
          id: number;
          order_id: string;
          actor_id: string | null;
          event: string;
          from_status: Database["public"]["Enums"]["order_status"] | null;
          to_status: Database["public"]["Enums"]["order_status"] | null;
          data: Json | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          order_id: string;
          actor_id?: string | null;
          event: string;
          from_status?: Database["public"]["Enums"]["order_status"] | null;
          to_status?: Database["public"]["Enums"]["order_status"] | null;
          data?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          order_id?: string;
          actor_id?: string | null;
          event?: string;
          from_status?: Database["public"]["Enums"]["order_status"] | null;
          to_status?: Database["public"]["Enums"]["order_status"] | null;
          data?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          user_id: string;
          type: Database["public"]["Enums"]["order_type"];
          service_id: string | null;
          plan_id: string;
          location_id: string;
          product: Database["public"]["Enums"]["product_type"];
          plan_name: string;
          plan_specs: Json;
          location_name: string;
          list_price_cents: number;
          discount_cents: number;
          total_cents: number;
          currency: string;
          term_days: number;
          coupon_id: string | null;
          coupon_code: string | null;
          status: Database["public"]["Enums"]["order_status"];
          expires_at: string;
          assigned_to: string | null;
          completed_at: string | null;
          cancelled_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_number?: string;
          user_id: string;
          type?: Database["public"]["Enums"]["order_type"];
          service_id?: string | null;
          plan_id: string;
          location_id: string;
          product: Database["public"]["Enums"]["product_type"];
          plan_name: string;
          plan_specs: Json;
          location_name: string;
          list_price_cents: number;
          discount_cents?: number;
          total_cents: number;
          currency?: string;
          term_days?: number;
          coupon_id?: string | null;
          coupon_code?: string | null;
          status?: Database["public"]["Enums"]["order_status"];
          expires_at: string;
          assigned_to?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_number?: string;
          user_id?: string;
          type?: Database["public"]["Enums"]["order_type"];
          service_id?: string | null;
          plan_id?: string;
          location_id?: string;
          product?: Database["public"]["Enums"]["product_type"];
          plan_name?: string;
          plan_specs?: Json;
          location_name?: string;
          list_price_cents?: number;
          discount_cents?: number;
          total_cents?: number;
          currency?: string;
          term_days?: number;
          coupon_id?: string | null;
          coupon_code?: string | null;
          status?: Database["public"]["Enums"]["order_status"];
          expires_at?: string;
          assigned_to?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      payment_methods: {
        Row: {
          id: string;
          name: string;
          type: Database["public"]["Enums"]["payment_method_type"];
          regions: string[];
          currency_code: string | null;
          rate_per_usd: number | null;
          rate_updated_at: string | null;
          fee_note: string | null;
          details: Json;
          qr_path: string | null;
          instructions_md: string | null;
          requires_reference: boolean;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: Database["public"]["Enums"]["payment_method_type"];
          regions?: string[];
          currency_code?: string | null;
          rate_per_usd?: number | null;
          rate_updated_at?: string | null;
          fee_note?: string | null;
          details?: Json;
          qr_path?: string | null;
          instructions_md?: string | null;
          requires_reference?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: Database["public"]["Enums"]["payment_method_type"];
          regions?: string[];
          currency_code?: string | null;
          rate_per_usd?: number | null;
          rate_updated_at?: string | null;
          fee_note?: string | null;
          details?: Json;
          qr_path?: string | null;
          instructions_md?: string | null;
          requires_reference?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          order_id: string;
          user_id: string;
          method_id: string;
          method_name: string;
          amount_usd_cents: number;
          quoted_currency: string | null;
          quoted_amount: number | null;
          quoted_rate: number | null;
          reference: string | null;
          note: string | null;
          proof_path: string;
          proof_sha256: string;
          proof_mime: string | null;
          proof_size: number | null;
          status: Database["public"]["Enums"]["payment_status"];
          received_usd_cents: number | null;
          reject_reason: string | null;
          reject_message: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          user_id: string;
          method_id: string;
          method_name: string;
          amount_usd_cents: number;
          quoted_currency?: string | null;
          quoted_amount?: number | null;
          quoted_rate?: number | null;
          reference?: string | null;
          note?: string | null;
          proof_path: string;
          proof_sha256: string;
          proof_mime?: string | null;
          proof_size?: number | null;
          status?: Database["public"]["Enums"]["payment_status"];
          received_usd_cents?: number | null;
          reject_reason?: string | null;
          reject_message?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          user_id?: string;
          method_id?: string;
          method_name?: string;
          amount_usd_cents?: number;
          quoted_currency?: string | null;
          quoted_amount?: number | null;
          quoted_rate?: number | null;
          reference?: string | null;
          note?: string | null;
          proof_path?: string;
          proof_sha256?: string;
          proof_mime?: string | null;
          proof_size?: number | null;
          status?: Database["public"]["Enums"]["payment_status"];
          received_usd_cents?: number | null;
          reject_reason?: string | null;
          reject_message?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      plan_pricing: {
        Row: {
          plan_id: string;
          location_id: string;
          price_cents: number;
          stock: Database["public"]["Enums"]["stock_status"];
          stock_count: number | null;
          is_active: boolean;
          updated_at: string;
        };
        Insert: {
          plan_id: string;
          location_id: string;
          price_cents: number;
          stock?: Database["public"]["Enums"]["stock_status"];
          stock_count?: number | null;
          is_active?: boolean;
          updated_at?: string;
        };
        Update: {
          plan_id?: string;
          location_id?: string;
          price_cents?: number;
          stock?: Database["public"]["Enums"]["stock_status"];
          stock_count?: number | null;
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      plans: {
        Row: {
          id: string;
          product: Database["public"]["Enums"]["product_type"];
          name: string;
          slug: string;
          vcpu: number;
          ram_gb: number;
          storage_gb: number;
          bandwidth_tb: number;
          port_mbps: number;
          features: string[];
          is_featured: boolean;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product: Database["public"]["Enums"]["product_type"];
          name: string;
          slug: string;
          vcpu: number;
          ram_gb: number;
          storage_gb: number;
          bandwidth_tb: number;
          port_mbps: number;
          features?: string[];
          is_featured?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          product?: Database["public"]["Enums"]["product_type"];
          name?: string;
          slug?: string;
          vcpu?: number;
          ram_gb?: number;
          storage_gb?: number;
          bandwidth_tb?: number;
          port_mbps?: number;
          features?: string[];
          is_featured?: boolean;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          phone: string | null;
          billing_country: string | null;
          company: string | null;
          telegram: string | null;
          whatsapp: string | null;
          role: Database["public"]["Enums"]["user_role"];
          status: Database["public"]["Enums"]["account_status"];
          suspended_reason: string | null;
          notification_prefs: Json;
          last_seen_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string;
          phone?: string | null;
          billing_country?: string | null;
          company?: string | null;
          telegram?: string | null;
          whatsapp?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          status?: Database["public"]["Enums"]["account_status"];
          suspended_reason?: string | null;
          notification_prefs?: Json;
          last_seen_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          phone?: string | null;
          billing_country?: string | null;
          company?: string | null;
          telegram?: string | null;
          whatsapp?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          status?: Database["public"]["Enums"]["account_status"];
          suspended_reason?: string | null;
          notification_prefs?: Json;
          last_seen_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      service_credentials: {
        Row: {
          service_id: string;
          username: string;
          password_enc: string;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          service_id: string;
          username: string;
          password_enc: string;
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: {
          service_id?: string;
          username?: string;
          password_enc?: string;
          updated_by?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      services: {
        Row: {
          id: string;
          user_id: string;
          order_id: string;
          plan_id: string;
          location_id: string;
          product: Database["public"]["Enums"]["product_type"];
          plan_name: string;
          plan_specs: Json;
          label: string;
          hostname: string | null;
          ip: string;
          rdp_port: number;
          status: Database["public"]["Enums"]["service_status"];
          suspended_reason: string | null;
          started_at: string;
          expires_at: string;
          terminated_at: string | null;
          inventory_item_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          order_id: string;
          plan_id: string;
          location_id: string;
          product: Database["public"]["Enums"]["product_type"];
          plan_name: string;
          plan_specs: Json;
          label: string;
          hostname?: string | null;
          ip: string;
          rdp_port?: number;
          status?: Database["public"]["Enums"]["service_status"];
          suspended_reason?: string | null;
          started_at?: string;
          expires_at: string;
          terminated_at?: string | null;
          inventory_item_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          order_id?: string;
          plan_id?: string;
          location_id?: string;
          product?: Database["public"]["Enums"]["product_type"];
          plan_name?: string;
          plan_specs?: Json;
          label?: string;
          hostname?: string | null;
          ip?: string;
          rdp_port?: number;
          status?: Database["public"]["Enums"]["service_status"];
          suspended_reason?: string | null;
          started_at?: string;
          expires_at?: string;
          terminated_at?: string | null;
          inventory_item_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      site_settings: {
        Row: {
          key: string;
          value: Json;
          is_public: boolean;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          key: string;
          value: Json;
          is_public?: boolean;
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: {
          key?: string;
          value?: Json;
          is_public?: boolean;
          updated_by?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      staff_notes: {
        Row: {
          id: string;
          entity_type: string;
          entity_id: string;
          author_id: string | null;
          body: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          entity_type: string;
          entity_id: string;
          author_id?: string | null;
          body: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          entity_type?: string;
          entity_id?: string;
          author_id?: string | null;
          body?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      ticket_messages: {
        Row: {
          id: string;
          ticket_id: string;
          author_id: string | null;
          author_role: Database["public"]["Enums"]["user_role"];
          body: string;
          is_internal: boolean;
          attachments: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          ticket_id: string;
          author_id?: string | null;
          author_role: Database["public"]["Enums"]["user_role"];
          body: string;
          is_internal?: boolean;
          attachments?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          ticket_id?: string;
          author_id?: string | null;
          author_role?: Database["public"]["Enums"]["user_role"];
          body?: string;
          is_internal?: boolean;
          attachments?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      tickets: {
        Row: {
          id: string;
          ticket_no: number;
          user_id: string;
          service_id: string | null;
          subject: string;
          category: Database["public"]["Enums"]["ticket_category"];
          priority: Database["public"]["Enums"]["ticket_priority"];
          status: Database["public"]["Enums"]["ticket_status"];
          assigned_to: string | null;
          last_message_at: string;
          last_customer_message_at: string | null;
          last_staff_message_at: string | null;
          resolved_at: string | null;
          closed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          ticket_no?: number;
          user_id: string;
          service_id?: string | null;
          subject: string;
          category?: Database["public"]["Enums"]["ticket_category"];
          priority?: Database["public"]["Enums"]["ticket_priority"];
          status?: Database["public"]["Enums"]["ticket_status"];
          assigned_to?: string | null;
          last_message_at?: string;
          last_customer_message_at?: string | null;
          last_staff_message_at?: string | null;
          resolved_at?: string | null;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          ticket_no?: number;
          user_id?: string;
          service_id?: string | null;
          subject?: string;
          category?: Database["public"]["Enums"]["ticket_category"];
          priority?: Database["public"]["Enums"]["ticket_priority"];
          status?: Database["public"]["Enums"]["ticket_status"];
          assigned_to?: string | null;
          last_message_at?: string;
          last_customer_message_at?: string | null;
          last_staff_message_at?: string | null;
          resolved_at?: string | null;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      payment_methods_public: {
        Row: {
          id: string | null;
          name: string | null;
          type: Database["public"]["Enums"]["payment_method_type"] | null;
          regions: string[] | null;
          sort_order: number | null;
        };
        Relationships: [];
      };
      services_v: {
        Row: {
          id: string | null;
          user_id: string | null;
          order_id: string | null;
          plan_id: string | null;
          location_id: string | null;
          product: Database["public"]["Enums"]["product_type"] | null;
          plan_name: string | null;
          plan_specs: Json | null;
          label: string | null;
          hostname: string | null;
          ip: string | null;
          rdp_port: number | null;
          status: Database["public"]["Enums"]["service_status"] | null;
          suspended_reason: string | null;
          started_at: string | null;
          expires_at: string | null;
          terminated_at: string | null;
          inventory_item_id: string | null;
          created_at: string | null;
          updated_at: string | null;
          effective_status: Database["public"]["Enums"]["service_status"] | null;
          days_left: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      admin_action_queue: { Args: Record<PropertyKey, never>; Returns: Json };
      admin_cancel_order: { Args: { p_order_id: string | null; p_reason: string | null }; Returns: Database["public"]["Tables"]["orders"]["Row"] };
      admin_kpis: { Args: { p_from: string | null; p_to: string | null }; Returns: Json };
      admin_revenue_series: { Args: { p_from: string | null; p_to: string | null; p_bucket?: string | null }; Returns: { bucket: string | null; revenue_cents: number | null; invoices: number | null }[] };
      allocate_service: { Args: { p_order_id: string | null; p_label: string | null; p_hostname: string | null; p_ip: string | null; p_port: number | null; p_username: string | null; p_password_enc: string | null; p_starts_at?: string | null; p_expires_at?: string | null; p_inventory_item_id?: string | null; p_expiry_reason?: string | null; p_notify?: boolean | null }; Returns: Database["public"]["Tables"]["services"]["Row"] };
      approve_payment: { Args: { p_payment_id: string | null; p_received_usd_cents: number | null }; Returns: Database["public"]["Tables"]["orders"]["Row"] };
      assign_ticket: { Args: { p_ticket_id: string | null; p_assignee: string | null }; Returns: Database["public"]["Tables"]["tickets"]["Row"] };
      bootstrap_first_admin: { Args: { p_email: string | null }; Returns: string };
      cancel_order: { Args: { p_order_id: string | null }; Returns: Database["public"]["Tables"]["orders"]["Row"] };
      cancel_stale_orders: { Args: Record<PropertyKey, never>; Returns: number };
      create_order: { Args: { p_plan_id: string | null; p_location_id: string | null; p_coupon_code?: string | null; p_renew_service_id?: string | null }; Returns: Database["public"]["Tables"]["orders"]["Row"] };
      create_ticket: { Args: { p_subject: string | null; p_category: Database["public"]["Enums"]["ticket_category"] | null; p_service_id: string | null; p_message: string | null; p_attachments?: Json | null }; Returns: Database["public"]["Tables"]["tickets"]["Row"] };
      enqueue_expiry_reminders: { Args: Record<PropertyKey, never>; Returns: number };
      expire_services: { Args: Record<PropertyKey, never>; Returns: number };
      extend_service: { Args: { p_service_id: string | null; p_days?: number | null; p_set_expires_at?: string | null; p_reason?: string | null }; Returns: Database["public"]["Tables"]["services"]["Row"] };
      flag_terminate_due: { Args: Record<PropertyKey, never>; Returns: number };
      get_service_credentials: { Args: { p_service_id: string | null }; Returns: { username: string | null; password_enc: string | null }[] };
      mark_order_refunded: { Args: { p_order_id: string | null; p_amount_cents: number | null; p_reason: string | null }; Returns: Database["public"]["Tables"]["orders"]["Row"] };
      preview_coupon: { Args: { p_plan_id: string | null; p_location_id: string | null; p_code: string | null }; Returns: { discount_cents: number | null; list_price_cents: number | null; total_cents: number | null }[] };
      reject_payment: { Args: { p_payment_id: string | null; p_reason: string | null; p_message?: string | null }; Returns: Database["public"]["Tables"]["orders"]["Row"] };
      rename_service: { Args: { p_service_id: string | null; p_label: string | null }; Returns: Database["public"]["Tables"]["services"]["Row"] };
      reply_to_ticket: { Args: { p_ticket_id: string | null; p_body: string | null; p_attachments?: Json | null }; Returns: Database["public"]["Tables"]["ticket_messages"]["Row"] };
      set_account_status: { Args: { p_user_id: string | null; p_status: Database["public"]["Enums"]["account_status"] | null; p_reason?: string | null }; Returns: Database["public"]["Tables"]["profiles"]["Row"] };
      set_ticket_fields: { Args: { p_ticket_id: string | null; p_status?: Database["public"]["Enums"]["ticket_status"] | null; p_priority?: Database["public"]["Enums"]["ticket_priority"] | null; p_category?: Database["public"]["Enums"]["ticket_category"] | null }; Returns: Database["public"]["Tables"]["tickets"]["Row"] };
      set_ticket_status_customer: { Args: { p_ticket_id: string | null; p_status: Database["public"]["Enums"]["ticket_status"] | null }; Returns: Database["public"]["Tables"]["tickets"]["Row"] };
      set_user_role: { Args: { p_user_id: string | null; p_role: Database["public"]["Enums"]["user_role"] | null }; Returns: Database["public"]["Tables"]["profiles"]["Row"] };
      staff_reply_to_ticket: { Args: { p_ticket_id: string | null; p_body: string | null; p_is_internal?: boolean | null; p_attachments?: Json | null }; Returns: Database["public"]["Tables"]["ticket_messages"]["Row"] };
      start_provisioning: { Args: { p_order_id: string | null }; Returns: Database["public"]["Tables"]["orders"]["Row"] };
      submit_payment: { Args: { p_order_id: string | null; p_method_id: string | null; p_proof_path: string | null; p_proof_sha256: string | null; p_mime: string | null; p_size: number | null; p_reference?: string | null; p_note?: string | null }; Returns: Database["public"]["Tables"]["payments"]["Row"] };
      suspend_service: { Args: { p_service_id: string | null; p_reason: string | null }; Returns: Database["public"]["Tables"]["services"]["Row"] };
      terminate_service: { Args: { p_service_id: string | null; p_reason: string | null }; Returns: Database["public"]["Tables"]["services"]["Row"] };
      unsuspend_service: { Args: { p_service_id: string | null }; Returns: Database["public"]["Tables"]["services"]["Row"] };
      update_service_credentials: { Args: { p_service_id: string | null; p_username: string | null; p_password_enc: string | null; p_notify?: boolean | null }; Returns: undefined };
      void_invoice: { Args: { p_invoice_id: string | null; p_reason: string | null }; Returns: Database["public"]["Tables"]["invoices"]["Row"] };
    };
    Enums: {
      account_status: "active" | "suspended";
      discount_type: "percent" | "fixed_usd";
      inventory_status: "available" | "allocated" | "retired";
      order_status: "awaiting_payment" | "under_review" | "approved" | "provisioning" | "completed" | "rejected" | "cancelled" | "refunded";
      order_type: "new" | "renewal";
      payment_method_type: "bank" | "mobile_wallet" | "upi" | "crypto" | "other";
      payment_status: "pending" | "verified" | "rejected";
      product_type: "rdp" | "vps";
      service_status: "active" | "suspended" | "expired" | "terminated";
      stock_status: "in_stock" | "low" | "out_of_stock";
      ticket_category: "billing" | "technical" | "order" | "restart_request" | "reinstall_request" | "cannot_connect" | "other";
      ticket_priority: "low" | "normal" | "high" | "urgent";
      ticket_status: "open" | "awaiting_customer" | "resolved" | "closed";
      user_role: "customer" | "support" | "admin";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

export const Constants = {
  public: {
    Enums: {
      account_status: ["active", "suspended"],
      discount_type: ["percent", "fixed_usd"],
      inventory_status: ["available", "allocated", "retired"],
      order_status: ["awaiting_payment", "under_review", "approved", "provisioning", "completed", "rejected", "cancelled", "refunded"],
      order_type: ["new", "renewal"],
      payment_method_type: ["bank", "mobile_wallet", "upi", "crypto", "other"],
      payment_status: ["pending", "verified", "rejected"],
      product_type: ["rdp", "vps"],
      service_status: ["active", "suspended", "expired", "terminated"],
      stock_status: ["in_stock", "low", "out_of_stock"],
      ticket_category: ["billing", "technical", "order", "restart_request", "reinstall_request", "cannot_connect", "other"],
      ticket_priority: ["low", "normal", "high", "urgent"],
      ticket_status: ["open", "awaiting_customer", "resolved", "closed"],
      user_role: ["customer", "support", "admin"],
    },
  },
} as const;

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type Views<T extends keyof PublicSchema["Views"]> = PublicSchema["Views"][T]["Row"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];
export type RpcArgs<T extends keyof PublicSchema["Functions"]> = PublicSchema["Functions"][T]["Args"];
export type RpcReturns<T extends keyof PublicSchema["Functions"]> = PublicSchema["Functions"][T]["Returns"];
