// Rewrites the countries and prices in supabase/seed.sql from src/content/launch.json, so a fresh database starts with exactly
// the catalog the built-in one (src/content/catalog.ts) shows.
//   node scripts/gen-launch.mjs
// Only the two blocks between the BEGIN/END markers are touched.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const launch = JSON.parse(readFileSync(path.join(root, "src/content/launch.json"), "utf8"));
const world = readFileSync(path.join(root, "src/content/world.ts"), "utf8");
const names = Object.fromEntries([...world.matchAll(/iso2: "([A-Z]{2})", name: "([^"]+)"/g)].map((m) => [m[1], m[2]]));

const slugify = (s) =>
  s
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
const sql = (s) => `'${s.replaceAll("'", "''")}'`;
const SKYLINE = { US: "loc-us", GB: "loc-uk", IN: "loc-in", BD: "loc-bd" };

const rows = launch.countries.map(([iso2, tier], i) => {
  const name = names[iso2];
  if (!name) throw new Error(`unknown country ${iso2}`);
  return { iso2, tier, name, slug: slugify(name), order: i + 1 };
});

const locations = `-- BEGIN launch locations (generated by scripts/gen-launch.mjs from src/content/launch.json)
insert into public.locations (name, slug, iso2, image_key, sort_order) values
${rows.map((r) => `  (${sql(r.name)}, ${sql(r.slug)}, ${sql(r.iso2)}, ${SKYLINE[r.iso2] ? sql(SKYLINE[r.iso2]) : "null"}, ${r.order})`).join(",\n")}
on conflict (slug) do nothing;
-- END launch locations`;

const tierRows = Object.entries(launch.tiers)
  .filter(([k]) => !k.startsWith("_"))
  .flatMap(([tier, prices]) => launch.plans.map((p, i) => `  (${sql(tier)}, ${sql(p.split("/")[0])}, ${sql(p.split("/")[1])}, ${prices[i]})`));

const pricing = `-- BEGIN launch pricing (generated by scripts/gen-launch.mjs from src/content/launch.json)
insert into public.plan_pricing (plan_id, location_id, price_cents)
select p.id, l.id, t.price * 100
from (values
${rows.map((r) => `  (${sql(r.slug)}, ${sql(r.tier)})`).join(",\n")}
) as c(loc_slug, tier)
join (values
${tierRows.join(",\n")}
) as t(tier, product, plan_slug, price) on t.tier = c.tier
join public.plans p on p.product = t.product::public.product_type and p.slug = t.plan_slug
join public.locations l on l.slug = c.loc_slug
on conflict (plan_id, location_id) do nothing;
-- END launch pricing`;

const file = path.join(root, "supabase/seed.sql");
let seed = readFileSync(file, "utf8");
const swap = (name, block) => {
  const re = new RegExp(`-- BEGIN launch ${name}[\\s\\S]*?-- END launch ${name}`);
  if (!re.test(seed)) throw new Error(`seed.sql has no "${name}" markers`);
  seed = seed.replace(re, () => block);
};
swap("locations", locations);
swap("pricing", pricing);
writeFileSync(file, seed);
console.log(`seed.sql: ${rows.length} countries, ${rows.length * launch.plans.length} prices`);
