"use client";

import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { getBrowserClient } from "@/lib/supabase/browser";

type Phase =
  | { step: "loading" }
  | { step: "enroll"; factorId: string; qr: string; secret: string }
  | { step: "challenge"; factorId: string }
  | { step: "error"; message: string };

const friendly = (message: string) =>
  /invalid|expired|incorrect/i.test(message) ? "That code didn't work. Check the 6 digits and try again — codes change every 30 seconds." : message;

/**
 * Second-factor step, shared by staff and customers. If the account has no authenticator yet it enrols one (QR code +
 * manual key), otherwise it asks for the current 6-digit code. Both paths end the same way: verify → the session becomes
 * AAL2 → continue to `next` (or, when `next` is null, just refresh the page you are on).
 * All of it talks to Supabase Auth directly from the browser; no secret ever passes through our servers.
 */
export function MfaPanel({ enrolled, next = "/admin" }: { enrolled: boolean; /** Where to go once verified. null = stay on this page and refresh it. */ next?: string | null }) {
  const router = useRouter();
  const [phase, setPhase] = useState<Phase>({ step: "loading" });
  const [code, setCode] = useState("");
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const started = useRef(false);

  useEffect(() => {
    if (started.current) return; // React strict mode runs effects twice in development; enrol only once
    started.current = true;
    const supabase = getBrowserClient();
    (async () => {
      const factors = await supabase.auth.mfa.listFactors();
      if (factors.error) return setPhase({ step: "error", message: "We couldn't reach the sign-in service. Refresh to try again." });
      const verified = factors.data.totp[0]; // `totp` only lists verified factors
      if (enrolled && verified) return setPhase({ step: "challenge", factorId: verified.id });

      // Clear half-finished enrolments from an earlier attempt, then start a fresh one.
      for (const f of factors.data.all.filter((x) => x.factor_type === "totp" && x.status === "unverified")) {
        await supabase.auth.mfa.unenroll({ factorId: f.id });
      }
      const enrol = await supabase.auth.mfa.enroll({ factorType: "totp", friendlyName: `Authenticator ${new Date().toISOString().slice(0, 10)}` });
      if (enrol.error) {
        return setPhase({ step: "error", message: "Two-step verification couldn't be set up. Make sure TOTP multi-factor is enabled for this project in Supabase → Authentication." });
      }
      setPhase({ step: "enroll", factorId: enrol.data.id, qr: enrol.data.totp.qr_code, secret: enrol.data.totp.secret });
    })();
  }, [enrolled]);

  async function verify(e: React.FormEvent) {
    e.preventDefault();
    if (phase.step !== "enroll" && phase.step !== "challenge") return;
    setBusy(true);
    setMessage(null);
    const supabase = getBrowserClient();
    const challenge = await supabase.auth.mfa.challenge({ factorId: phase.factorId });
    if (challenge.error) {
      setBusy(false);
      return setMessage(friendly(challenge.error.message));
    }
    const result = await supabase.auth.mfa.verify({ factorId: phase.factorId, challengeId: challenge.data.id, code: code.trim() });
    if (result.error) {
      setBusy(false);
      setCode("");
      return setMessage(friendly(result.error.message));
    }
    if (next) router.replace(next);
    router.refresh();
    if (!next) setBusy(false);
  }

  if (phase.step === "loading") {
    return <p className="text-[15px] text-muted">Preparing…</p>;
  }
  if (phase.step === "error") {
    return (
      <p role="alert" className="form-note" data-tone="error">
        {phase.message}
      </p>
    );
  }

  return (
    <form onSubmit={verify} className="space-y-6" noValidate>
      {phase.step === "enroll" && (
        <div className="space-y-5">
          <ol className="space-y-2 text-[15px] leading-relaxed text-ink-2">
            <li>
              <span className="num-tabular mr-2 font-semibold text-lav-700">1</span>Open an authenticator app (Google Authenticator, 1Password, Authy…).
            </li>
            <li>
              <span className="num-tabular mr-2 font-semibold text-lav-700">2</span>Scan this code, or type the key below.
            </li>
            <li>
              <span className="num-tabular mr-2 font-semibold text-lav-700">3</span>Enter the 6-digit code it shows.
            </li>
          </ol>
          {/* The QR is an SVG data URI generated by Supabase Auth for this enrolment only. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={phase.qr} alt="QR code for your authenticator app" width={176} height={176} className="border border-line bg-white p-2" />
          <p className="text-[13px] text-muted">
            Can&apos;t scan? Enter this key instead:{" "}
            <span className="data-id select-all break-all font-semibold text-ink">{phase.secret}</span>
          </p>
        </div>
      )}

      <div className="field">
        <label htmlFor="mfa-code" className="field-label">
          6-digit code
        </label>
        <input
          id="mfa-code"
          className="field-input num-tabular tracking-[0.3em]"
          inputMode="numeric"
          autoComplete="one-time-code"
          pattern="[0-9]{6}"
          maxLength={6}
          required
          autoFocus
          value={code}
          onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
          aria-invalid={message ? true : undefined}
          aria-describedby={message ? "mfa-error" : undefined}
        />
        {message && (
          <p id="mfa-error" role="alert" className="field-error">
            {message}
          </p>
        )}
      </div>

      <Button type="submit" loading={busy} disabled={code.length !== 6}>
        {phase.step === "enroll" ? "Turn on and continue" : "Verify and continue"}
      </Button>
    </form>
  );
}
